"""empty message

Revision ID: 64ceb2b4f18a
Revises: fe0549f183df
Create Date: 2022-06-04 22:57:54.384950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64ceb2b4f18a'
down_revision = 'fe0549f183df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=mysql.VARCHAR(length=1028),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1028),
               existing_nullable=True)
    # ### end Alembic commands ###
